### ISSUE TITLE
Process has died with no error

### ISSUE THREAD

**Issue by linwk20** [APRIL-ZJU/OA-LICalib#6]
Hi, Thanks for you sharing of this great work!
When I run `roslaunch oa_licalib li_calib.launch`,I encounter process has died ERROR as shown below, however, no other errors are shown, so it make it hard to debug it
Can anyone help me? Thanks!

![image](https://user-images.githubusercontent.com/86647905/187505797-d9f6d42b-b3d0-47e6-835c-e88643ac4b94.png)

**Comment by yuhang9803** [comment]
Hi,did you solve this problem, I encountered this error too

**Comment by af-doom** [comment]
> Hi,did you solve this problem, I encountered this error too

I also have this question.
